sonar.projectKey=home-management
sonar.projectName=Home Management
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts,src/environments/**,src/test-setup-vitest.ts
sonar.javascript.lcov.reportPaths=coverage/home-management/lcov.info
sonar.testExecutionReportPaths=coverage/home-management/sonar-report.xml
sonar.sourceEncoding=UTF-8
