sonar.projectKey=Memija_home-management
sonar.organization=memija
sonar.projectName=Home Management
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts,src/environments/**,src/test-setup-vitest.ts
sonar.javascript.lcov.reportPaths=coverage/home-management/lcov.info
sonar.sourceEncoding=UTF-8
