import { HelpStep } from '../shared/help-modal/help-modal.component';

export const RECORD_HELP_STEPS: HelpStep[] = [
  { titleKey: 'ELECTRICITY.RECORD_HELP_STEP_1_TITLE', descriptionKey: 'ELECTRICITY.RECORD_HELP_STEP_1_DESC' },
  { titleKey: 'ELECTRICITY.RECORD_HELP_STEP_2_TITLE', descriptionKey: 'ELECTRICITY.RECORD_HELP_STEP_2_DESC' },
  { titleKey: 'ELECTRICITY.RECORD_HELP_STEP_3_TITLE', descriptionKey: 'ELECTRICITY.RECORD_HELP_STEP_3_DESC' },
  { titleKey: 'ELECTRICITY.RECORD_HELP_STEP_4_TITLE', descriptionKey: 'ELECTRICITY.RECORD_HELP_STEP_4_DESC' }
];

export const CHART_HELP_STEPS: HelpStep[] = [
  { titleKey: 'ELECTRICITY.CHART_HELP_STEP_1_TITLE', descriptionKey: 'ELECTRICITY.CHART_HELP_STEP_1_DESC' },
  { titleKey: 'ELECTRICITY.CHART_HELP_STEP_2_TITLE', descriptionKey: 'ELECTRICITY.CHART_HELP_STEP_2_DESC' },
  { titleKey: 'ELECTRICITY.CHART_HELP_STEP_3_TITLE', descriptionKey: 'ELECTRICITY.CHART_HELP_STEP_3_DESC' },
  { titleKey: 'ELECTRICITY.CHART_HELP_STEP_4_TITLE', descriptionKey: 'ELECTRICITY.CHART_HELP_STEP_4_DESC' }
];

export const RECORDS_LIST_HELP_STEPS: HelpStep[] = [
  { titleKey: 'ELECTRICITY.RECORDS_HELP_STEP_1_TITLE', descriptionKey: 'ELECTRICITY.RECORDS_HELP_STEP_1_DESC' },
  { titleKey: 'ELECTRICITY.RECORDS_HELP_STEP_2_TITLE', descriptionKey: 'ELECTRICITY.RECORDS_HELP_STEP_2_DESC' },
  { titleKey: 'ELECTRICITY.RECORDS_HELP_STEP_3_TITLE', descriptionKey: 'ELECTRICITY.RECORDS_HELP_STEP_3_DESC' },
  { titleKey: 'ELECTRICITY.RECORDS_HELP_STEP_4_TITLE', descriptionKey: 'ELECTRICITY.RECORDS_HELP_STEP_4_DESC' },
  { titleKey: 'ELECTRICITY.RECORDS_HELP_STEP_5_TITLE', descriptionKey: 'ELECTRICITY.RECORDS_HELP_STEP_5_DESC' }
];
