import { ErrorHandler, Injectable } from '@angular/core';

/**
 * List of error message fragments that originate from browser extensions
 * and are completely outside our application's control.
 * Silencing them prevents noise in the console and error monitoring tools.
 */
const EXTENSION_ERROR_PATTERNS: readonly string[] = [
  'Could not establish connection. Receiving end does not exist',
  'Extension context invalidated',
  'The message port closed before a response was received',
];

/**
 * Custom global error handler that filters out well-known browser-extension
 * errors before delegating to the default Angular error handler behaviour.
 *
 * The `runtime.lastError` / "Receiving end does not exist" family of errors is
 * generated by Chrome extensions (e.g. ad-blockers, password managers) when
 * their background service worker goes idle.  They are completely unrelated to
 * the application and would otherwise flood the console because Angular 21+'s
 * `provideBrowserGlobalErrorListeners()` captures *all* unhandled rejections.
 */
@Injectable({ providedIn: 'root' })
export class GlobalErrorHandlerService extends ErrorHandler {
  override handleError(error: unknown): void {
    if (this.isBrowserExtensionError(error)) {
      return; // Silently ignore — not our code
    }

    super.handleError(error);
  }

  private isBrowserExtensionError(error: unknown): boolean {
    const message = this.extractMessage(error);
    if (!message) return false;

    return EXTENSION_ERROR_PATTERNS.some((pattern) => message.includes(pattern));
  }

  private extractMessage(error: unknown): string | null {
    if (typeof error === 'string') return error;
    if (error instanceof Error) return error.message;
    if (error && typeof error === 'object' && 'message' in error) {
      return String((error as { message: unknown }).message);
    }
    return null;
  }
}
