name: zizmor GitHub Actions Security Scan

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  zizmor:
    name: CI/CD Workflow Security Audit
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@v0.6.3

